public class ChatGPT {
    //chat gpt secret key
    //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
// Organization - ID
// org-fWHGbIDuznPgM4wo3dpqOZHl

//https://www.salesforceben.com/integrating-openais-chatgpt-with-the-salesforce-appexchange/

//rubesh git 016
    
    
    
}